news_sites:
  eluniversal:
    url: https://www.eluniversal.com.co/
    queries:
      homepage_article_links: '.info a'
      article_body: '.paragraph'
      article_title: '.titulo-interna span'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.c_t a'
      article_body: '.a_c'
      article_title: '.a_t'